#+TITLE: Emacs Configuration
* What is this?

  This literate file represents my current configuration of Emacs! I
  am using literate programming to make it easier to document the
  strange and arcane things that I sometimes have to do while learning
  more about Emacs. Hopefully this makes it easier to maintain and
  change in the future.

* Pre-configuration

  Before I actually configure anything interesting, I need to do
  certain things (like install use-package). In this section, do not
  assume that anything has been installed, but configure things that
  are generic (at least in theory) to any configuration of Emacs.

** package.el

   First up, I have to make sure that [[https://repo.or.cz/w/emacs.git/blob_plain/HEAD:/lisp/emacs-lisp/package.el][package.el]] is
   configured. Package.el is a package manager that's built into GNU
   Emacs (apparently since Emacs24). I will be using `use-package` for
   the most part, but I will have to bootstrap that somehow and for
   now package.el (which is built in anywhere I have needed it) fits
   fine.

   #+BEGIN_SRC emacs-lisp
     (require 'package)
   #+END_SRC 

*** Package repositories

    By default, my Emacs distribution uses [[http://elpa.gnu.org/][ELPA]] , but I also want to
    use [[https://melpa.org/][MELPA]], so I will include that here.  

    #+BEGIN_SRC emacs-lisp
      (add-to-list 'package-archives
		   '("melpa" . "https://melpa.org/packages/") t)
    #+END_SRC
*** Initialization

    To set up `package.el` I need to call `package-initialize`.
    
    #+BEGIN_SRC emacs-lisp
      (package-initialize)
    #+END_SRC

** Use-package

   Now that package.el is set up, I can finally install and use
   `use-package`! [[https://github.com/jwiegley/use-package/tree/a7422fb8ab1baee19adb2717b5b47b9c3812a84c#use-package][Use-package]] is a crazy macro that does a lot of
   things but I am primarily using it to lazy-load things (using
   `package.el`) and to consolidate the list of plugins I am using
   with their configuration. I am also using the installation of
   `use-package` as an indicator that this is the first run. I don't
   want to refresh packages every time I start up Emacs, that would
   take forever, so I am refreshing them if use-package is not already
   installed. If it isn't, then clearly my config hasn't been run
   before, so we should refresh package contents before doing the
   initial setup.

   #+BEGIN_SRC emacs-lisp
     (unless (package-installed-p 'use-package)
       (package-refresh-contents)
       (package-install 'use-package))
   #+END_SRC

   Also, when we are compiling packages, we want to make sure that
   use-package has been loaded.

   #+BEGIN_SRC emacs-lisp
     (eval-when-compile
       (require 'use-package))
   #+END_SRC
* Configuration
  
  This is where the meat-and-potatoes of my configuratoin will live.
** Variables

   In this section, I set global settings that are specific to native
   emacs, rather than to a particular package.

   #+BEGIN_SRC emacs-lisp
     (tool-bar-mode -1)
     (menu-bar-mode -1)
     (scroll-bar-mode -1)
   #+END_SRC
** Utilities

   Grabs the current file name from the buffer.  Based on answer [[https://unix.stackexchange.com/questions/45125/how-to-get-current-buffers-filename-in-emacs][here]].

   #+BEGIN_SRC emacs-lisp
     (defun insert-file-name ()
       "Insert the file name into the current buffer (at point)."
       (interactive)
       (insert (buffer-file-name (window-buffer (minibuffer-selected-window)))))
   #+END_SRC
** Local configuration

   This file is set up only so that you can set any local variables
   you might need.  For example, if you are loading on Windows you
   might need to set some file paths to your org files that are
   different from the defaults I have checked in. If this file exists
   (and it should be ignored in the Git repo) then Emacs will tangle
   and execute it just like this file. If not, it will ignore and
   continue. 

   #+BEGIN_SRC emacs-lisp
     (setq local-file-path "~/.emacs.d/local.org")
     (if (file-exists-p local-file-path)
	 (org-babel-load-file local-file-path))
   #+END_SRC

** Packages
*** Evil-mode

    Evil mode is the vim emulation layer.  I am using use-package to
    install and enable it. 
    
**** Evil itself

     #+BEGIN_SRC emacs-lisp
       (use-package evil
	 :ensure t
	 :bind
	 (:map evil-normal-state-map
	       ("SPC SPC" . 'execute-extended-command)
	       ("SPC <tab>" . 'previous-buffer)
	       ("SPC <S-tab>" . 'next-buffer)
	       ("SPC f s" . 'save-buffer)
	       ("SPC l l" . 'eval-last-sexp)
	       ("SPC l b" . 'eval-buffer)
	       ("SPC l r" . 'eval-region)
	       ("SPC w h" . 'evil-window-left)
	       ("SPC w j" . 'evil-window-down)
	       ("SPC w k" . 'evil-window-up)
	       ("SPC w l" . 'evil-window-right)
	       ("SPC w H" . 'evil-window-move-far-left)
	       ("SPC w J" . 'evil-window-move-far-down)
	       ("SPC w K" . 'evil-window-move-far-up)
	       ("SPC w L" . 'evil-window-move-far-right)
	       ("SPC w s" . 'evil-window-split)
	       ("SPC w v" . 'evil-window-vsplit)
	       ("SPC w d" . 'evil-window-delete)
	       ("SPC w o" . 'other-window)
	       ("SPC w m" . 'delete-other-windows)
	       ("SPC b d" . 'kill-buffer)
	       ("SPC q f" . 'save-buffers-kill-terminal)
	       ("SPC h f" . 'describe-function)
	       ("SPC h v" . 'describe-variable)
	       ("SPC h k" . 'describe-key)
	       ("SPC h n" . 'view-emacs-news)
	       ("SPC h m" . 'describe-mode)
	       ("SPC h M" . 'view-order-manuals))
	 :init
	 (setq evil-want-keybinding nil)
	 (setq evil-want-C-u-scroll t)
	 :config
	 (evil-mode 1))
     #+END_SRC

**** Evil-collection

     We also want to use [[https://github.com/emacs-evil/evil-collection][`evil-collection`]] to set up things for
     "buffers evil mode doesn't think about by default"

     #+BEGIN_SRC emacs-lisp
       (use-package evil-collection
	 :after evil
	 :ensure t
	 :config
	 (evil-collection-init))
     #+END_SRC

**** Evil-surround

     Want to surround strings or expressions with things? This is how!

     #+BEGIN_SRC emacs-lisp
       (use-package evil-surround
	 :after evil
	 :ensure t
	 :config (global-evil-surround-mode))
     #+END_SRC

**** Evil-cleverparens

     [[https://github.com/luxbock/evil-cleverparens][This package]] is really helpful generally for writing Elisp. It
     has a bunch of features but it shold auto-close parens, and
     generally make evil mode actions aware of the syntax of lisp.

     #+BEGIN_SRC emacs-lisp
       (use-package evil-cleverparens
	 :after evil
	 :ensure t
	 :hook ( emacs-lisp-mode . evil-cleverparens-mode ))

     #+END_SRC

**** TODO Undo-tree

     Undo tree is a huge plugin whose features I am probably not using
     properly. For now I am using it only because undo functionality
     in Emacs 27 w/ Evil seems to need it. I should spend some time
     investigating features. Also, once I switch to Emacs 28, I may be
     able to use a native option.
     
     #+BEGIN_SRC emacs-lisp
       (use-package undo-tree
	 :ensure t
	 :after evil
	 :diminish
	 :config
	 (evil-set-undo-system 'undo-tree)
	 (global-undo-tree-mode 1))
     #+END_SRC
*** Company-mode

    [[http://company-mode.github.io/][Company mode]] is an auto complete plugin (*comp*-lete
    *any*-thing). I am still exploring how it can be used.
     #+BEGIN_SRC emacs-lisp
       (use-package company
	 :ensure t
	 :hook (after-init . global-company-mode)
	 :config
	 (setq company-idle-delay 0)
	 (setq company-minimum-prefix-length 1)
	 (setq company-selection-wrap-around t)
	 (company-tng-configure-default))
    #+END_SRC
*** Solarized-theme

    The solarized theme I am using is from MELPA. 

    #+BEGIN_SRC emacs-lisp
      (use-package solarized-theme
	:ensure t
	:config
	(load-theme 'solarized-dark t))
    #+END_SRC

*** Which key mode

    Which key is a pannel at the bottom that should display options
    when a key is pressed.

    #+BEGIN_SRC emacs-lisp
      (use-package which-key
	:ensure t
	:config
	(which-key-mode))
    #+END_SRC
*** IDO-mode

    IDO mode is a completion engine. There are two other primary
    engines that people use: [[https://emacs-helm.github.io/helm/][Heml]] and [[https://github.com/abo-abo/swiper][Ivy]]. I'm not really sure what
    the advantages of either are, but Mastering Emacs suggests IDO. I
    have used Helm in Spacemacs before, so I may later switch to that.

    #+BEGIN_SRC emacs-lisp
      (use-package ido
	:ensure t
	:config
	(setq ido-enable-flex-matching t)
	(setq ido-everywhere t)
	(ido-mode 1)
	(setq ido-use-filename-at-point 'guess)
	:bind
	(:map evil-normal-state-map
	      ("SPC f f" . 'ido-find-file)
	      ("SPC b b" . 'ido-switch-buffer)))
    #+END_SRC

    Also, I dislike that ido mode organizes itself horizontally, and
    want it to not do that.

    #+BEGIN_SRC emacs-lisp
      (use-package ido-vertical-mode
	:ensure t
	:after ido
	:config
	(ido-vertical-mode 1))
    #+END_SRC
*** Magit

    I love [[https://magit.vc/][Magit]]. Enough said.

    #+BEGIN_SRC emacs-lisp
      (use-package magit
	:ensure t
	:bind
	(:map evil-normal-state-map
	      ("SPC g s" . 'magit-status)))
    #+END_SRC
*** Org mode
    
**** TODO Temporary org mode config block

     I stole this from my old config and just threw it in a function
     so it doesn't junk things up. Now I need to work on refactoring
     it.
     
***** Org mode agenda files
      
      Note, you will probably want to override these variables in your
      local config.
      
      #+BEGIN_SRC emacs-lisp :tangle no :noweb-ref org-global-vars
	(defvar org-directory nil) ; Set this in your local.org file!
	(defvar org-jira-link "") ; Set this in your local.org file!
      #+END_SRC

      First up, I need to define what my org mode agenda files
      are. I'm going to wind up using these all over the place, so I
      am going to define them all together

      #+BEGIN_SRC emacs-lisp :tangle no :noweb-ref org-agenda-file-names
	(setq todo-org "todo.org")
	(setq professional-org "professional.org")
	(setq personal-org "personal.org")
	(setq school-org "school.org")
	(setq notes-org "notes.org")
	(setq inbox-org "inbox.org")
	(setq project-org "project.org")
	(setq reviews-org "reviews.org")
	(setq meetings-org "meetings.org")
	(setq interruption-org "interruption.org")
	(setq contact-log-org "contact-log.org")
	(setq one_on_one_topics-org "one-on-one-topics.org")
      #+END_SRC
      
      Once I have those variables, I am going to want to concatenate
      the path to my org files to them. To enable that, we should
      write a handly little method
      
      #+BEGIN_SRC emacs-lisp
	(defun org-concat-org-directory (fileName)
	  (concat org-directory fileName))
      #+END_SRC
      
      #+BEGIN_SRC emacs-lisp :tangle no :noweb-ref org-agenda-set-up
	(add-to-list 'org-agenda-files (org-concat-org-directory todo-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory professional-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory personal-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory school-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory notes-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory inbox-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory project-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory meetings-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory interruption-org))
	(add-to-list 'org-agenda-files (org-concat-org-directory contact-log-org))
      #+END_SRC
      

      
***** Org datetree functions

      I have two custom date-tree functions that I wrote to make
      capture templates easier to work with. These were based on [[https://emacs.stackexchange.com/questions/48414/monthly-date-tree][this]].
      
      First up, this tree is a "datetree" only to the month.
      #+BEGIN_SRC emacs-lisp
	(defun org-month-datetree()
	  (org-datetree-find-date-create (calendar-current-date))
	  ;; Kill the line because this date tree will involve a subheading for the week
	  (kill-line))
      #+END_SRC
      
      Next up, a date tree th a week
      #+BEGIN_SRC emacs-lisp
	(defun org-week-datetree()
	  (org-datetree-find-iso-week-create (calendar-current-date))
	  ;; Kill the line because this date tree will involve a subheading for the day
	  (kill-line))
      #+END_SRC
***** The junk
     
     #+BEGIN_SRC emacs-lisp :noweb yes
       (defun org-variables-config()
       
         <<org-global-vars>>

	 <<org-agenda-file-names>>

	 <<org-agenda-set-up>>

	 (setq org-capture-templates
	       `(("t"
		  "Todo"
		  entry
		  (file ,(concat org-directory inbox-org))
		  "* TODO %?\n  %i\n  %a")

		 ("n"
		  "Note to self"
		  entry
		  (file+headline ,(concat org-directory notes-org) "Note to Self")
		  "* %?\nEntered on %U\n  %i\n  %a")

		 ("i"
		  "interruption"
		  entry
		  (file+datetree ,(concat org-directory interruption-org))
		  "* Interrupted by %?\n%t")

		 ("c"
		  "contact"
		  entry
		  (file+datetree ,(concat org-directory contact-log-org))
		  "* Contacted by: %\\1%?
		    :PROPERTIES:
		    :NAME:       %^{Name}
		    :COMPANY:    %^{Company}
		    :HEADHUNTER: %^{Headhunter|Y|N}
		    :SOURCE:     %^{Source|LinedIn|Phone|Email}
		    :END:")

		 ("w" "Templates around office/work stuff")

		 ("wo"
		  "one on one topics"
		  plain ; also unsure what plain actually means
		  (file+function ,(concat org-directory one_on_one_topics-org) org-week-datetree)
		  "*** %?" ; note the 3 asterisks.  Would be nice to figure out how to do that without but eh.
		  )
		 ("wQ"
		  "Datebase Query"
		  entry
		  (file ,(concat org-directory inbox-org))
		  "* %\\2%?
		    :PROPERTIES:
		    :DATABASE: %^{database|STATIC_TABLES|TENANTS}
		    :TICKET:   %^{ticket}
		    :TYPE:     %^{type|DATA|POST_MIGRATION}
		    :END:
		    ,,#+BEGIN_SRC sql :tangle %\\2-%\\1-%\\3.txt
		    ,,#+END_SRC
		    ")
		 ("wj"
		  "Jira ticket"
		  entry
		  (file ,(concat org-directory inbox-org))
		  ,(concat "* TODO %\\1%?
		    [[" org-jira-link "%^{ticket}][%\\1]]"))

		 ("wm"
		  "Meeting notes"
		  entry
		  (file+datetree ,(concat org-directory meetings-org))
		  "* %?\n%U\n")
		 ))
	 )

       ;; Agenda configuration
       (setq org-agenda-span 14)
       (setq org-refile-targets (quote ((nil :maxlevel . 5)
					(org-agenda-files :maxlevel . 5))))

       ;; Sets the org-repeat logbook to store its information in the "LOGBOOK" drawer instead of in a bulleted list on the header. this should keep things cleaner
       (setq org-log-into-drawer "LOGBOOK")

       (setq org-todo-keywords
	     '((sequence "TODO(t)" "WAITING(w)" "|" "DONE(d)" "CANCELED(c)")))

       (setq org-log-repeat nil)

     #+END_SRC

**** Require package

    #+BEGIN_SRC emacs-lisp
      (use-package org
	:ensure t
	:config
	(org-variables-config)
	(evil-define-key 'normal org-mode-map (kbd "SPC m i l") 'org-insert-link)
	(evil-define-key 'normal org-mode-map (kbd "SPC m d s") 'org-schedule)
	(evil-define-key 'normal org-mode-map (kbd "SPC m d d") 'org-deadline)
	(evil-define-key 'normal org-mode-map (kbd "SPC m s r") 'org-refile)
	(evil-define-key 'normal org-mode-map (kbd "SPC m s n") 'org-narrow-to-subtree)
	(evil-define-key 'normal org-mode-map (kbd "SPC m s w") 'widen)
	(evil-define-key 'normal org-mode-map (kbd "SPC m p") 'org-priority)
	(evil-define-key 'normal org-mode-map (kbd "SPC m C i") 'org-clock-in)
	(evil-define-key 'normal org-mode-map (kbd "SPC m C o") 'org-clock-out)
	(evil-define-key 'normal org-mode-map (kbd "SPC m i i") 'org-insert-item)
	(evil-define-key 'edit 'org-mode-map (kbd "<M-return>") 'org-insert-item)
	(evil-define-key 'normal org-mode-map (kbd "SPC m T T") 'org-todo)
	(evil-define-key 'normal org-mode-map (kbd "SPC m i t") 'org-set-tags-command)
	:bind
	(:map evil-normal-state-map
	      ("SPC a o a" . 'org-agenda)
	      ("SPC a o c" . 'org-capture)))
    #+END_SRC

**** evil-org

     #+BEGIN_SRC emacs-lisp
       (use-package evil-org
	 :ensure t
	 :after org
	 :hook (org-mode . (lambda () evil-org-mode))
	 :config
	 (require 'evil-org-agenda)
	 (evil-org-agenda-set-keys))
     #+END_SRC

**** Org bullets

     A really cool plugin that makes pretty bullets

     #+BEGIN_SRC emacs-lisp
       (use-package org-bullets
	 :after org
	 :ensure t
	 :config
	 (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
     #+END_SRC

*** Editorconfig
    
    Editorconfig is a standard for keeping code editing settings in
    sync across tools and teams.  Someone can check in a .Editorconfig
    file at the root of a repo, and their editors should respect the
    settings. This should do that for me!

    #+BEGIN_SRC emacs-lisp
      (use-package editorconfig
	:ensure t
	:config
	(editorconfig-mode 1))
    #+END_SRC
*** Smartparens

    #+BEGIN_SRC emacs-lisp
      (use-package smartparens
	:ensure t
	:hook ( emacs-lisp-mode . smartparens-mode))
    #+END_SRC
*** Web mode

    #+BEGIN_SRC emacs-lisp
      (use-package web-mode
	:ensure t
	:config
	(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
	(evil-define-key 'normal web-mode-map (kbd "SPC m <tab>") 'web-mode-fold-or-unfold)
	(evil-define-key 'normal web-mode-map (kbd "SPC m i l") 'web-mode-file-link)
	(evil-define-key 'normal web-mode-map (kbd "SPC m g t") 'web-mode-navigate)
	(evil-define-key 'normal web-mode-map (kbd "SPC m g j") 'web-mode-tag-next)
	(evil-define-key 'normal web-mode-map (kbd "SPC m g k") 'web-mode-tag-previous))
    #+END_SRC
*** Zettelkasten

    This is a plugin that isn't in MELPA for now, and I can't seem to
    convince it to load by adding it to ~load-path~ so I am instead
    going to manually require it.
    #+BEGIN_SRC emacs-lisp
      (require 'zettelkasten-mode "~/.emacs.d/plugins/zettelkasten/zettelkasten.el")
    #+END_SRC

    To actually configure it, though, I still want to use
    ~use-package~, so now that it's loaded, I can use ~use-package~ to
    activate it and set up the basic keybindings. Yay, some consistency!
    
    #+BEGIN_SRC emacs-lisp
      (use-package zettelkasten-mode
	:bind
	(:map evil-normal-state-map
	      ("SPC a z c" . 'zettel-create-new))
	:config
	(zettelkasten-mode 1))
    #+END_SRC
*** TODO Markdown-mode

    I use Markdown for quite a lot, so I need a markdown mode. This
    one could probably be configured more.

    #+BEGIN_SRC emacs-lisp
      (use-package markdown-mode
	:ensure t
	:config
	(evil-define-key 'normal markdown-mode-map (kbd "SPC m i f") 'markdown-insert-footnote))
    #+END_SRC
*** Python mode

    #+BEGIN_SRC emacs-lisp
      (use-package python-mode
	:ensure t)
    #+END_SRC
*** Vue mode

    I need a major mode for Vue files!

    #+BEGIN_SRC emacs-lisp
      (use-package vue-mode
	:ensure t)
    #+END_SRC
* Sources

  + [[https://masteringemacs.org/article/beginners-guide-to-emacs][Mastering Emacs Beginners Guide]]
